"""add node workspace parent index

Revision ID: 502337caef5e
Revises: b05b882d123e
Create Date: 2026-09-30 11:51:45.896468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502337caef5e'
down_revision: Union[str, Sequence[str], None] = 'b05b882d123e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_nodes_workspace_parent', 'nodes', ['workspace_id', 'parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nodes_workspace_parent', table_name='nodes')
    # ### end Alembic commands ###
