"""add component system

Revision ID: bb004bf395b6
Revises: df2eb60d21f3
Create Date: 2026-10-01 16:08:16.488719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb004bf395b6'
down_revision: Union[str, Sequence[str], None] = 'df2eb60d21f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('definition_key', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('binding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_components_workspace_id_id')
    )
    op.create_table('component_placements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('parent_placement_id', sa.UUID(), nullable=True),
    sa.Column('slot_key', sa.String(length=255), nullable=True),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('size', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transform', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'component_id'], ['components.workspace_id', 'components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'page_id'], ['nodes.workspace_id', 'nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'parent_placement_id'], ['component_placements.workspace_id', 'component_placements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_component_placements_workspace_id_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_placements')
    op.drop_table('components')
    # ### end Alembic commands ###
