"""remove node type

Revision ID: d40b02eb016b
Revises: 502337caef5e
Create Date: 2026-10-01 15:08:54.345072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40b02eb016b'
down_revision: Union[str, Sequence[str], None] = '502337caef5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column(
        "nodes",
        sa.Column(
            "type",
            sa.VARCHAR(length=50),
            nullable=True,
        ),
    )
