"""add page settings

Revision ID: df2eb60d21f3
Revises: d40b02eb016b
Create Date: 2026-10-01 15:32:48.074351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df2eb60d21f3'
down_revision: Union[str, Sequence[str], None] = 'd40b02eb016b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_settings',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('appearance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('layout_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('behavior_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_settings')
    # ### end Alembic commands ###
